[package]
name = "sparkle_os"
version = "0.1.0"
authors = ["Erin <erin@hashbang.sh>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
spin = "0.4.5"
volatile = "0.2"
x86 = "0.8"
multiboot2 = "0.3.2"
bitflags = "0.9"

[dependencies.log]
version = "0.3"
default-features = false
