[package]
name = "sparkle_os"
version = "0.1.0"
authors = ["Erin <erin@hashbang.sh>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.2"
spin = "0.4.6"
x86_64 = "0.1.2"
multiboot2 = "0.3.2"
bitflags = "0.9"
linked_list_allocator = "0.5"
raw-cpuid = "3.0.0"
bit_field = "0.8.0"

[dependencies.log]
version = "0.3"
default-features = false

[dependencies.lazy_static]
version = "0.2.9"
features = ["spin_no_std"]

[dependencies.once]
path = "lib/once"
