[package]
name = "sparkle_os"
version = "0.1.0"
authors = ["Erin <erin@hashbang.sh>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.2"
x86 = "0.8"
multiboot2 = "0.3.2"
bitflags = "0.9"

[dependencies.spin]
git = "https://github.com/messense/spin-rs"
rev = "020f1b3"

[dependencies.log]
version = "0.3"
default-features = false
